export interface IRibbonItem {
  iconCss?: string;
  items?: { iconCss?: string, text?: string }[];
  isToggle?: boolean;
  content?: string;
  cssClass?: string;
  clicked?: () => void;
  dataSource?: string[];
  index?: number;
  width?: string;
  allowFiltering?: boolean;
  value?: string;
  label?: string;
  checked?: boolean;
  menuItems?: IMenuItem[];
  visible?: boolean;
  target?: string;
  createPopupOnClick?: boolean;
}

interface IMenuItem {
  id?: string;
  text?: string;
  items?: IMenuItem[];
}

export interface IRibbon {
  groupButtonIcon: IRibbonItem;
  pasteSettings: IRibbonItem;
  cutButton: IRibbonItem;
  deleteButton: IRibbonItem;
  exportButton: IRibbonItem;
  undoButton: IRibbonItem;
  copyButton: IRibbonItem;
  formatButton: IRibbonItem;
  boldButton: IRibbonItem;
  alignLeftButton: IRibbonItem;
  alginCenterButton: IRibbonItem;
  alignRightButton: IRibbonItem;
  italicButton: IRibbonItem;
  underlineButton: IRibbonItem;
  strikethroughButton: IRibbonItem;
  changecaseButton: IRibbonItem;
  fillButton: IRibbonItem;
  lineButton: IRibbonItem;
  textButton: IRibbonItem;
  startButton: IRibbonItem;
  endButton: IRibbonItem;
  pointerButton: IRibbonItem;
  text2Button: IRibbonItem;
  line2Button: IRibbonItem;
  rectangularButton: IRibbonItem;
  curvedLineButton: IRibbonItem;
  ellipseButton: IRibbonItem;
  ascendantButton: IRibbonItem;
  autoConnectorButton: IRibbonItem;
  nodeSplitButton: IRibbonItem;
  chartButton: IRibbonItem;
  printButton: IRibbonItem;
  webButton: IRibbonItem;
  fontstyleSettings: IRibbonItem;
  fontsizeSettings: IRibbonItem;
  colorSettings: IRibbonItem;
  ruler: IRibbonItem;
  grid?: IRibbonItem;
  navigation: IRibbonItem;
  fileSettings: IRibbonItem;
  containerSettings: IRibbonItem;
  containerDropdownData: { id?: string, text?: string, img?: string }[];
  listSettings: IRibbonItem;
  listDropdownData: { group: string, items: { id?: string, text?: string, img?: string, group: string }[] }[];
  pictureButton: IRibbonItem;
  fromClipboardButton: IRibbonItem;
  funcButton: IRibbonItem;
  applicationSettings: IRibbonItem;
  resultButton: IRibbonItem;
  collectionButton: IRibbonItem;
  dictionaryButton: IRibbonItem;
  areaButton: IRibbonItem;
  funcDropdown: IRibbonItem;
  functionDropdownData: { id?: string, text?: string, img?: string }[];
  wordDropdown: IRibbonItem;
  wordDropdownData: { id?: string, text?: string, img?: string }[];
  applicationDropdown: IRibbonItem;
  applicationDropdownData: { id?: string, text?: string, img?: string }[];
  relationshipDropdown: IRibbonItem;
  relationshipDropdownData: { id?: string, text?: string, img?: string }[];
  theory1Dropdown: IRibbonItem;
  theory1DropdownData: { id?: string, text?: string, img?: string }[];
  theory2Dropdown: IRibbonItem;
  theory2DropdownData: { id?: string, text?: string, img?: string }[];
  fundamentalDropdown: IRibbonItem;
  fundamentalDropdownData: { id?: string, text?: string, img?: string }[];
  fundamental2Dropdown: IRibbonItem;
  fundamental2DropdownData: { id?: string, text?: string, img?: string }[];
  theoryFunctionDropdown: IRibbonItem;
  theoryFunctionDropdownData: { id?: string, text?: string, img?: string }[];
  timeDropdown: IRibbonItem;
  timeDropdownData: { id?: string, text?: string, img?: string }[];
  derivativeDropdown: IRibbonItem;
  derivativeDropdownData: { id?: string, text?: string, img?: string }[];
  instrumentDropdown: IRibbonItem;
  instrumentDropdownData: { id?: string, text?: string, img?: string }[];
  stabilityDropdown: IRibbonItem;
  stabilityDropdownData: { id?: string, text?: string, img?: string }[];
  theoremDropdown: IRibbonItem;
  theoremDropdownData: { id?: string, text?: string, img?: string }[];
  bracketDropdown: IRibbonItem;
  bracketDropdownData: { id?: string, text?: string, img?: string }[];
  decoratorDropdown: IRibbonItem;
  decoratorDropdownData: { id?: string, text?: string, img?: string }[];
  sumProductDropdown: IRibbonItem;
  sumDropdownData: { id?: string, text?: string, img?: string }[];
  integralDropdown: IRibbonItem;
  integralDropdownData: { id?: string, text?: string, img?: string }[];
  scriptDropdown: IRibbonItem;
  scriptDropdownData: { id?: string, text?: string, img?: string }[];
  factionRadicalDropdown: IRibbonItem;
  fracDropdownData: { id?: string, text?: string, img?: string }[];
  labeledArrowDropdown: IRibbonItem;
  arrowDropdown: IRibbonItem;
  arrowDropdownData: { id?: string, text?: string, img?: string }[];
  underbarOverbarDropdown: IRibbonItem;
  barDropdownData: { id?: string, text?: string, img?: string }[];
  accentPrimeDropdown: IRibbonItem;
  accentDropdownData: { id?: string, text?: string, img?: string }[];
  matrixDropdown: IRibbonItem;
  matrixDropdownData: { id?: string, text?: string, img?: string }[];
  boxesDropdown: IRibbonItem;
  boxesDropdownData: { id?: string, text?: string, img?: string }[];
  operatorDropdown: IRibbonItem;
  operatorDropdownData: { id?: string, text?: string, img?: string }[];
  greekCapitalDropdown: IRibbonItem;
  greekCapitalDropdownData: { id?: string, text?: string, img?: string }[];
  greekSmallDropdown: IRibbonItem;
  greekSmallDropdownData: { id?: string, text?: string, img?: string }[];
  arrowCodeDropdownData: { id?: string, text?: string, img?: string }[];
  undoLastActionButton: IRibbonItem;
  communicationButton: IRibbonItem;
  theoryButton: IRibbonItem;
  startProjectButton: IRibbonItem;
  configureWarningMsgButton: IRibbonItem;
  applicationSettingButton: IRibbonItem;
  captureImgButton: IRibbonItem;
  editImgButton: IRibbonItem;
  recordVideoButton: IRibbonItem;
  editVideoButton: IRibbonItem;
  recordAudioButton: IRibbonItem;
  settingsButton: IRibbonItem;
  simulateButton: IRibbonItem;
  debugButton: IRibbonItem;
  stepIntoButton: IRibbonItem;
  abortButton: IRibbonItem;
  stopButton: IRibbonItem;
  simulationSettingButton: IRibbonItem;
  closeProjectButton: IRibbonItem;
  openProjectButton: IRibbonItem;
  subFuncButton: IRibbonItem;
  subApplicationButton: IRibbonItem;
  subResultButton: IRibbonItem;
  fitWindowButton: IRibbonItem;
  pageWidthButton: IRibbonItem;
  showTooltipButton: IRibbonItem;
  allowCrossButton: IRibbonItem;
  imgWidthFrameButton: IRibbonItem;
  rulerButton: IRibbonItem;
  gridButton: IRibbonItem;
  pageBreakButton: IRibbonItem;
  entityLibraryButton: IRibbonItem;
  panZoomButton: IRibbonItem;
  modelViewButton: IRibbonItem;
  viewListButton: IRibbonItem;
  showHideModelButton: IRibbonItem;
  showHideConnectionPointButton: IRibbonItem;
  panToolButton: IRibbonItem;
  arrowLeftButton: IRibbonItem;
  arrowRightButton: IRibbonItem;
  arrowUpButton: IRibbonItem;
  arrowDownButton: IRibbonItem;
  align1Button: IRibbonItem;
  align2Button: IRibbonItem;
  align3Button: IRibbonItem;
  align4Button: IRibbonItem;
  align5Button: IRibbonItem;
  align6Button: IRibbonItem;
  equalHorizonButton: IRibbonItem;
  equalVerticalButton: IRibbonItem;
  increaseHorizonButton: IRibbonItem;
  increaseVerticalButton: IRibbonItem;
  decreaseHorizonButton: IRibbonItem;
  decreaseVerticalButton: IRibbonItem;
  sameWidthButton: IRibbonItem;
  sameHeightButton: IRibbonItem;
  sameSizeButton: IRibbonItem;
  snapGridButton: IRibbonItem;
  snapRulerButton: IRibbonItem;
  snapGuideLineButton: IRibbonItem;
  modelHorizonButton: IRibbonItem;
  modelVerticalButton: IRibbonItem;
  sizeToWindowPointButton: IRibbonItem;
  selectedEntityButton: IRibbonItem;
}
