export enum EDiagramAction {
  COPY = 'COPY',
  PARSE = 'PARSE'
}

export enum EDiagramModel {
  //COMMUNICATION
  COMM_MAIN_PROJECT_MODEL = 'COMM_MAIN_PROJECT_MODEL',
  COMM_PROBLEM_STATEMENT = 'COMM_PROBLEM_STATEMENT',
  //THEORY
  THEORY_MAIN_APPLICATION_MODEL = 'THEORY_MAIN_APPLICATION_MODEL',
  SYSTEM_APPLY_THEORY_MODEL = 'SYSTEM_APPLY_THEORY_MODEL',
}
